/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proiectpoo;

/**
 *
 * @author tb173
 */
public class TudorUI extends javax.swing.JFrame {
    
    Calculator[] vectorCalculatoare = TestTudor.getCalculator();
    Desktop[] vectorDesktop = TestTudor.getDesktop();
    Server[] vectorServer = TestTudor.getServer();

    /**
     * Creates new form TudorUI
     */
    public TudorUI() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        afisareVectorCalculatoare = new javax.swing.JButton();
        textCalculatoare = new java.awt.TextArea();
        label1 = new java.awt.Label();
        textDesktop = new java.awt.TextArea();
        afisareVectorServer = new javax.swing.JButton();
        textServer = new java.awt.TextArea();
        label3 = new java.awt.Label();
        textPlacaDeBaza = new java.awt.TextField();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        textStocare = new java.awt.TextField();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        textNrProcesoare = new java.awt.TextField();
        textNrPorturi = new java.awt.TextField();
        label10 = new java.awt.Label();
        label2 = new java.awt.Label();
        textMouse = new java.awt.TextField();
        label6 = new java.awt.Label();
        textAlimentare = new java.awt.TextField();
        afisareVectorDesktop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1000, 900));
        setResizable(false);

        afisareVectorCalculatoare.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        afisareVectorCalculatoare.setText("Afiseaza vectorul de Calculatoare");
        afisareVectorCalculatoare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afisareVectorCalculatoareActionPerformed(evt);
            }
        });

        textCalculatoare.setEditable(false);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label1.setText("Afisare Vector Calculatoare");

        textDesktop.setBackground(new java.awt.Color(255, 255, 255));
        textDesktop.setEditable(false);

        afisareVectorServer.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        afisareVectorServer.setText("Afiseaza vectorul de Servere");
        afisareVectorServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afisareVectorServerActionPerformed(evt);
            }
        });

        textServer.setBackground(new java.awt.Color(255, 255, 255));
        textServer.setEditable(false);

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label3.setText("Afisare Vector Servere");

        textPlacaDeBaza.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textPlacaDeBaza.setName(""); // NOI18N

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label4.setText("Scrie noul nume pentru Placa de Baza:");

        label5.setAlignment(java.awt.Label.CENTER);
        label5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label5.setMinimumSize(new java.awt.Dimension(220, 21));
        label5.setPreferredSize(new java.awt.Dimension(220, 21));
        label5.setText("Scrie noua valoare pentru stocare:");

        textStocare.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textStocare.setName(""); // NOI18N

        label8.setAlignment(java.awt.Label.CENTER);
        label8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label8.setText("Scrie noua valoare pentru Nr. Porturi USB:");

        label9.setAlignment(java.awt.Label.CENTER);
        label9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label9.setMinimumSize(new java.awt.Dimension(220, 21));
        label9.setText("Scrie noua valoare pentru Nr. Procesoare:");

        textNrProcesoare.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textNrProcesoare.setName(""); // NOI18N

        textNrPorturi.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textNrPorturi.setName(""); // NOI18N

        label10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label10.setText("Afisare Vector Desktop-uri");

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label2.setText("Scrie noul nume pentru Mouse:");

        label6.setAlignment(java.awt.Label.CENTER);
        label6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label6.setText("Scrie nou valoare pentru Alimentare:");

        afisareVectorDesktop.setText("Afiseaza vectorul de Desktop-uri");
        afisareVectorDesktop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afisareVectorDesktopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(afisareVectorCalculatoare)
                                        .addGap(41, 41, 41)
                                        .addComponent(textDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textServer, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(label5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(59, 59, 59)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(textPlacaDeBaza, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(textStocare, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(142, 142, 142)
                                                .addComponent(textMouse, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(57, 57, 57))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(afisareVectorDesktop))
                                                        .addGap(15, 15, 15))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(textAlimentare, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(57, 57, 57))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(26, 26, 26)))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(label8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(textNrProcesoare, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(64, 64, 64))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(textNrPorturi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(62, 62, 62))
                                                    .addComponent(label9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(50, 50, 50)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(afisareVectorServer)
                                                .addGap(15, 15, 15)))
                                        .addGap(37, 37, 37))))
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(textCalculatoare, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textPlacaDeBaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textStocare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textMouse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textAlimentare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(afisareVectorCalculatoare)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textCalculatoare, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(afisareVectorDesktop)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNrPorturi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textNrProcesoare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(afisareVectorServer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textServer, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void afisareVectorCalculatoareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afisareVectorCalculatoareActionPerformed
        textCalculatoare.setText("");
        
        if(!textPlacaDeBaza.getText().equals("") && !textStocare.getText().equals("")){
            for(Calculator c : vectorCalculatoare){
                if(c.getNumePlacaDeBaza().contains(textPlacaDeBaza.getText()) && c.getStocare() == Short.parseShort(textStocare.getText())){
                    textCalculatoare.append(c.toString());
                }
            }
        }
        else if(!textPlacaDeBaza.getText().equals("")){
            for(Calculator c : vectorCalculatoare){
                if(c.getNumePlacaDeBaza().contains(textPlacaDeBaza.getText())){
                    textCalculatoare.append(c.toString());
                }
            }
        }
        else if(!textStocare.getText().equals("")){
            for(Calculator c : vectorCalculatoare){
                if(c.getStocare() == Short.parseShort(textStocare.getText())){
                    textCalculatoare.append(c.toString());
                }
            }
        }
        if(textPlacaDeBaza.getText().equals("") && textStocare.getText().equals("")){
            for(Calculator c : vectorCalculatoare){
                textCalculatoare.append(c.toString());
            }
        }
        
    }//GEN-LAST:event_afisareVectorCalculatoareActionPerformed

    private void afisareVectorServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afisareVectorServerActionPerformed
        textServer.setText("");
        
        if(!textNrPorturi.getText().equals("") && !textNrProcesoare.getText().equals("")){
            for(Server s : vectorServer){
                if(Byte.parseByte(textNrPorturi.getText()) == s.getNrPorturiUSB() && Byte.parseByte(textNrProcesoare.getText()) == s.getNrProcesoare()){
                    textServer.append(s.toString());
                }
            }
        }
        else if(!textNrPorturi.getText().equals("")){
            for(Server s : vectorServer){
                if(Byte.parseByte(textNrPorturi.getText()) == s.getNrPorturiUSB()){
                    textServer.append(s.toString());
                }
            }
        }
        else if(!textNrProcesoare.getText().equals("")){
            for(Server s : vectorServer){
                if(Byte.parseByte(textNrProcesoare.getText()) == s.getNrProcesoare()){
                    textServer.append(s.toString());
                }
            }
        }
        if(textNrPorturi.getText().equals("") && textNrProcesoare.getText().equals("")){
            for(Server s : vectorServer){
                textServer.append(s.toString());
            }
        }
    }//GEN-LAST:event_afisareVectorServerActionPerformed

    private void afisareVectorDesktopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afisareVectorDesktopActionPerformed
        textDesktop.setText("");
        
        if(!textMouse.getText().equals("") && !textAlimentare.getText().equals("")){
            for(Desktop d : vectorDesktop){
                if(d.getNumeMouse().contains(textMouse.getText()) && d.getSursaAlimentare() == Short.parseShort(textAlimentare.getText())){
                    textDesktop.append(d.toString());
                }
            }
        }
        else if(!textMouse.getText().equals("")){
            for(Desktop d : vectorDesktop){
                if(d.getNumeMouse().contains(textMouse.getText())){
                    textDesktop.append(d.toString());
                }
            }
        }
        else if(!textAlimentare.getText().equals("")){
            for(Desktop d : vectorDesktop){
                if(d.getSursaAlimentare() == Short.parseShort(textAlimentare.getText())){
                    textDesktop.append(d.toString());
                }
            }
        }
        if(textMouse.getText().equals("") && textAlimentare.getText().equals("")){
            for(Desktop d : vectorDesktop){
                textDesktop.append(d.toString());
            }
        }
    }//GEN-LAST:event_afisareVectorDesktopActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TudorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TudorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TudorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TudorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TudorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton afisareVectorCalculatoare;
    private javax.swing.JButton afisareVectorDesktop;
    private javax.swing.JButton afisareVectorServer;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.TextField textAlimentare;
    private java.awt.TextArea textCalculatoare;
    private java.awt.TextArea textDesktop;
    private java.awt.TextField textMouse;
    private java.awt.TextField textNrPorturi;
    private java.awt.TextField textNrProcesoare;
    private java.awt.TextField textPlacaDeBaza;
    private java.awt.TextArea textServer;
    private java.awt.TextField textStocare;
    // End of variables declaration//GEN-END:variables
}
