/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proiectpoo;

/**
 *
 * @author va195
 */
public class ValentinaUI extends javax.swing.JFrame {

    Calculator[] vectorCalculatoare = TestValentina.getCalculator();
    Laptop[] vectorLaptop = TestValentina.getLaptop();
    AccesoriiLaptop[] vectorAccesoriiLaptop = TestValentina.getAccesoriiLaptop();
    /**
     * Creates new form ValentinaUI
     */
    public ValentinaUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        textPlacaVideo = new java.awt.TextField();
        textAlimentare = new java.awt.TextField();
        afisareVectorCalculatoare = new javax.swing.JButton();
        textVectorLaptop = new java.awt.TextArea();
        textVectorCalculator = new java.awt.TextArea();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        textBaterie = new java.awt.TextField();
        textRAM = new java.awt.TextField();
        afisareVectorLaptop = new javax.swing.JButton();
        label7 = new java.awt.Label();
        textVectorAccesoriiLaptop = new java.awt.TextArea();
        label8 = new java.awt.Label();
        textAreCasti = new java.awt.TextField();
        label9 = new java.awt.Label();
        textAreProtectieEcran = new java.awt.TextField();
        afisareVectorAccesoriiLaptop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(950, 900));

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label1.setText("Afisare Vector Laptopuri");

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label2.setText("Cauta dupa Alimentare:");

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label3.setText("Cauta dupa Placa Video:");

        textPlacaVideo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textPlacaVideo.setForeground(new java.awt.Color(255, 102, 255));

        textAlimentare.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textAlimentare.setForeground(new java.awt.Color(255, 102, 255));

        afisareVectorCalculatoare.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        afisareVectorCalculatoare.setText("Afiseaza Vectorul de Calculatoare");
        afisareVectorCalculatoare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afisareVectorCalculatoareActionPerformed(evt);
            }
        });

        textVectorLaptop.setEditable(false);
        textVectorLaptop.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        textVectorCalculator.setEditable(false);
        textVectorCalculator.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        label4.setAlignment(java.awt.Label.CENTER);
        label4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label4.setText("Afisare Vector Calculatoare");

        label5.setAlignment(java.awt.Label.CENTER);
        label5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label5.setText("Cauta dupa Memorie RAM:");

        label6.setAlignment(java.awt.Label.CENTER);
        label6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label6.setText("Cauta dupa Autonomie Baterie:");

        textBaterie.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textBaterie.setForeground(new java.awt.Color(255, 102, 255));

        textRAM.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textRAM.setForeground(new java.awt.Color(255, 102, 255));

        afisareVectorLaptop.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        afisareVectorLaptop.setText("Afiseaza Vectorul de Laptopuri");
        afisareVectorLaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afisareVectorLaptopActionPerformed(evt);
            }
        });

        label7.setAlignment(java.awt.Label.CENTER);
        label7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label7.setText("Afisare Vector Accesorii Laptop");

        textVectorAccesoriiLaptop.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        label8.setAlignment(java.awt.Label.CENTER);
        label8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label8.setName(""); // NOI18N
        label8.setText("Cauta daca are Casti:");

        textAreCasti.setForeground(new java.awt.Color(255, 102, 255));

        label9.setAlignment(java.awt.Label.CENTER);
        label9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        label9.setName(""); // NOI18N
        label9.setText("Cauta daca are Protectie Ecran:");

        textAreProtectieEcran.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        textAreProtectieEcran.setForeground(new java.awt.Color(255, 102, 255));

        afisareVectorAccesoriiLaptop.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        afisareVectorAccesoriiLaptop.setText("Afiseaza Vectorul de Accesorii Laptop");
        afisareVectorAccesoriiLaptop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afisareVectorAccesoriiLaptopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textVectorCalculator, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textVectorLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(afisareVectorCalculatoare))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(textPlacaVideo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(textAlimentare, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(afisareVectorLaptop))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(textRAM, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(textBaterie, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textVectorAccesoriiLaptop, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(afisareVectorAccesoriiLaptop))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(textAreProtectieEcran, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(textAreCasti, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(139, 139, 139))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textPlacaVideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textAlimentare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(afisareVectorCalculatoare))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textAreCasti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textAreProtectieEcran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(afisareVectorLaptop)
                                    .addComponent(afisareVectorAccesoriiLaptop)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textBaterie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textRAM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textVectorLaptop, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addComponent(textVectorCalculator, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
                    .addComponent(textVectorAccesoriiLaptop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void afisareVectorCalculatoareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afisareVectorCalculatoareActionPerformed
        textVectorCalculator.setText("");
        
        if(!textPlacaVideo.getText().equals("") && !textAlimentare.getText().equals("")){
            for(Calculator c : vectorCalculatoare){
                if(c.getNumePlacaVideo().contains(textPlacaVideo.getText()) && c.getSursaAlimentare() == Short.parseShort(textAlimentare.getText())){
                    textVectorCalculator.append(c.toString());
                    textVectorCalculator.append(System.getProperty("line.separator")); // Pentru a asigura portabilitatea codului pentru orice sistem de operare
                    textVectorCalculator.append("\n"); // Salt de linie, indiferent de platforma
                }
            }
        }
        else if(!textPlacaVideo.getText().equals("")){
            for(Calculator c : vectorCalculatoare){
                if(c.getNumePlacaVideo().contains(textPlacaVideo.getText())){
                    textVectorCalculator.append(c.toString());
                    textVectorCalculator.append(System.getProperty("line.separator")); // Pentru a asigura portabilitatea codului pentru orice sistem de operare
                    textVectorCalculator.append("\n"); // Salt de linie, indiferent de platforma
                }
            }
        }
        else if(!textAlimentare.getText().equals("")){
            for(Calculator c : vectorCalculatoare){
                if(c.getSursaAlimentare() == Short.parseShort(textAlimentare.getText())){
                    textVectorCalculator.append(c.toString());
                    textVectorCalculator.append(System.getProperty("line.separator")); // Pentru a asigura portabilitatea codului pentru orice sistem de operare
                    textVectorCalculator.append("\n"); // Salt de linie, indiferent de platforma
                }
            }
        }
        if(textPlacaVideo.getText().equals("") && textAlimentare.getText().equals("")){
            for(Calculator c : vectorCalculatoare){
                textVectorCalculator.append(c.toString());
                textVectorCalculator.append(System.getProperty("line.separator")); // Pentru a asigura portabilitatea codului pentru orice sistem de operare
                textVectorCalculator.append("\n"); // Salt de linie, indiferent de platforma
            }
        }
    }//GEN-LAST:event_afisareVectorCalculatoareActionPerformed

    private void afisareVectorLaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afisareVectorLaptopActionPerformed
        textVectorLaptop.setText("");

        if(!textBaterie.getText().equals("") && !textRAM.getText().equals("")){
            for(Laptop l : vectorLaptop){
                if(l.getAutonomieBaterie() == Byte.parseByte(textBaterie.getText()) && l.getMemorieRam() == Byte.parseByte(textRAM.getText())){
                    textVectorLaptop.append(l.toString());
                    textVectorLaptop.append(System.getProperty("line.separator")); // Pentru a asigura portabilitatea codului pentru orice sistem de operare
                    textVectorLaptop.append("\n"); // Salt de linie, indiferent de platforma
                }
            }
        }
        else if(!textBaterie.getText().equals("")){
            for(Laptop l : vectorLaptop){
                if(l.getAutonomieBaterie() == Byte.parseByte(textBaterie.getText())){
                    textVectorLaptop.append(l.toString());
                    textVectorLaptop.append(System.getProperty("line.separator")); // Pentru a asigura portabilitatea codului pentru orice sistem de operare
                    textVectorLaptop.append("\n"); // Salt de linie, indiferent de platforma
                }
            }
        }
        else if(!textRAM.getText().equals("")){
            for(Laptop l : vectorLaptop){
                if(l.getMemorieRam() == Byte.parseByte(textRAM.getText())){
                    textVectorLaptop.append(l.toString());
                    textVectorLaptop.append(System.getProperty("line.separator")); // Pentru a asigura portabilitatea codului pentru orice sistem de operare
                    textVectorLaptop.append("\n"); // Salt de linie, indiferent de platforma
                }
            }
        }
        if(textBaterie.getText().equals("") && textRAM.getText().equals("")){
            for(Laptop l : vectorLaptop){
                textVectorLaptop.append(l.toString());
                textVectorLaptop.append(System.getProperty("line.separator")); // Pentru a asigura portabilitatea codului pentru orice sistem de operare
                textVectorLaptop.append("\n"); // Salt de linie, indiferent de platforma
            }
        }
    }//GEN-LAST:event_afisareVectorLaptopActionPerformed

    private void afisareVectorAccesoriiLaptopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afisareVectorAccesoriiLaptopActionPerformed
        textVectorAccesoriiLaptop.setText("");

        if(!textAreCasti.getText().equals("") && !textAreProtectieEcran.getText().equals("")){
            for(AccesoriiLaptop a : vectorAccesoriiLaptop){
                if(a.getAreCasti() == Boolean.parseBoolean(textAreCasti.getText()) && a.getAreProtectieEcran() == Boolean.parseBoolean(textAreProtectieEcran.getText())){
                    textVectorAccesoriiLaptop.append(a.toString());
                    textVectorAccesoriiLaptop.append(System.getProperty("line.separator")); // Pentru a asigura portabilitatea codului pentru orice sistem de operare
                    textVectorAccesoriiLaptop.append("\n"); // Salt de linie, indiferent de platforma
                }
            }
        }
        else if(!textAreCasti.getText().equals("")){
            for(AccesoriiLaptop a : vectorAccesoriiLaptop){
                if(a.getAreCasti() == Boolean.parseBoolean(textAreCasti.getText())){
                    textVectorAccesoriiLaptop.append(a.toString());
                    textVectorAccesoriiLaptop.append(System.getProperty("line.separator")); // Pentru a asigura portabilitatea codului pentru orice sistem de operare
                    textVectorAccesoriiLaptop.append("\n"); // Salt de linie, indiferent de platforma
                }
            }
        }
        else if(!textAreProtectieEcran.getText().equals("")){
            for(AccesoriiLaptop a : vectorAccesoriiLaptop){
                if(a.getAreProtectieEcran() == Boolean.parseBoolean(textAreProtectieEcran.getText())){
                    textVectorAccesoriiLaptop.append(a.toString());
                    textVectorAccesoriiLaptop.append(System.getProperty("line.separator")); // Pentru a asigura portabilitatea codului pentru orice sistem de operare
                    textVectorAccesoriiLaptop.append("\n"); // Salt de linie, indiferent de platforma
                }
            }
        }
        if(textAreCasti.getText().equals("") && textAreProtectieEcran.getText().equals("")){
            for(AccesoriiLaptop a : vectorAccesoriiLaptop){
                textVectorAccesoriiLaptop.append(a.toString());
                textVectorAccesoriiLaptop.append(System.getProperty("line.separator")); // Pentru a asigura portabilitatea codului pentru orice sistem de operare
                textVectorAccesoriiLaptop.append("\n"); // Salt de linie, indiferent de platforma
            }
        }
    }//GEN-LAST:event_afisareVectorAccesoriiLaptopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValentinaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValentinaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValentinaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValentinaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValentinaUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton afisareVectorAccesoriiLaptop;
    private javax.swing.JButton afisareVectorCalculatoare;
    private javax.swing.JButton afisareVectorLaptop;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.TextField textAlimentare;
    private java.awt.TextField textAreCasti;
    private java.awt.TextField textAreProtectieEcran;
    private java.awt.TextField textBaterie;
    private java.awt.TextField textPlacaVideo;
    private java.awt.TextField textRAM;
    private java.awt.TextArea textVectorAccesoriiLaptop;
    private java.awt.TextArea textVectorCalculator;
    private java.awt.TextArea textVectorLaptop;
    // End of variables declaration//GEN-END:variables
}
